#!/bin/bash

# Show faiure message
drivers(){
    echo -en " 
\E[1;33;44m
Failed to insert TBS drivers to the build system

Aborting...
\E[0m

"
    exit 1
}

# Add TBS drivers to the build system
cp -f v4l-6680/* ../media_build/v4l/

if [ "$?" -eq 1 ]; then
  drivers
fi

cp -f dvb-frontends-6680/* ../media_build/linux/drivers/media/dvb-frontends/

if [ "$?" -eq 1 ]; then
  drivers
fi

mkdir -p ../media_build/linux/drivers/media/common/saa716x
cp -f saa716x-6680/* ../media_build/linux/drivers/media/common/saa716x/

if [ "$?" -eq 1 ]; then
  drivers
fi

sed -i "$ a\
obj-\$(CONFIG_SAA716X_CORE) += saa716x/" ../media_build/linux/drivers/media/common/Makefile
sed -i "$ a\
source \"drivers/media/common/saa716x/Kconfig\"" ../media_build/linux/drivers/media/common/Kconfig
sed -i "$ a\
obj-\$(CONFIG_DVB_TBS6680FE) += tbs6680fe.o" ../media_build/linux/drivers/media/dvb-frontends/Makefile
sed -i "$ a\
tbs6680fe-objs += kmem_wrap.o tbs6680fe_driver.o" ../media_build/linux/drivers/media/dvb-frontends/Makefile

cd ../media_build && patch -p1 < ../tbs-v4l/kconfig_patch_6680 && cd ../tbs-v4l

if [ "$?" -eq 1 ]; then
  drivers
fi

# Compile prep
if [ `getconf LONG_BIT` = "64" ]
then
  echo "
Setting up TBS drivers for a amd64 system
"
  cd ../media_build && sh v4l/tbs-x86_64.sh
  if [ "$?" -eq 1 ]; then
    echo -en "
\E[1;33;44m
Faild to setup TBS drivers for amd64 system.

Aborting...
\E[0m

"
    cd ../tbs-v4l &&  exit 1
  fi
  cd ../tbs-v4l
else
  echo "
Setting up TBS drivers for a i386 system
"
  cd ../media_build && sh v4l/tbs-x86_r3.sh
  if [ "$?" -eq 1 ]; then
    echo -en "
\E[1;33;44m
Faild to setup TBS drivers for i386 system.

Aborting...
\E[0m

"
    cd ../tbs-v4l &&  exit 1
  fi
  cd ../tbs-v4l
fi

